[cassandra] Set default keyspace for client connections
Summary:
Set a default keyspace for new client connections instead of
requiring the client to send `set_keyspace()`. This makes connections
stateless, which will allow SR to handle retries instead of pycassa.

Test Plan:
Built it, deployed on cassandraproxyhomefeed1-frc with
`-Dcassandra.default_client_keyspace=homefeed`.

    $ python -c 'from pycassa.connection import Connection; from pycassa.cassandra.ttypes import *; c=Connection("homefeed", "cassandraproxyhomefeed2-frc"); c.get("foo", ColumnPath("FeedActivitiesByUserID", None, "quaz"), ConsistencyLevel.ONE)'
    pycassa.cassandra.ttypes.InvalidRequestException: InvalidRequestException(why='No keyspace has been specified. USE a keyspace, or explicitly specify keyspace.tablename')
    $ python -c 'from pycassa.connection import Connection; from pycassa.cassandra.ttypes import *; c=Connection("homefeed", "cassandraproxyhomefeed1-frc"); c.get("foo", ColumnPath("FeedActivitiesByUserID", None, "quaz"), ConsistencyLevel.ONE)'
    pycassa.cassandra.ttypes.InvalidRequestException: InvalidRequestException(why='UUID should be 16 or 0 bytes (4)')

Reviewers: rbranson, dikang

Reviewed By: dikang

Differential Revision: https://phabricator.fb.com/D2281873

Signature: t1:2281873:1438713173:1f76020b9c03ac82007cebfe7a04c147ccdc0e87